# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "2b1f38dc-4f72-45d8-b365-6b904b769cb8"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  cocoapods

  desc "Submit to HockeyApp"
  # Download status: "1" = No user can download; "2" = Available for download
  lane :hockeyApp do
      hockey(
        ipa:"../build/Zombiefy2016.ipa",
        dsym: "../build/Zombiefy2016.zip",
        api_token: "31047ed37b2e4303acf93989f3e07386",
        notify: "0",
        release_type: "0",
        status: "2",
        notes: "New build"
      )
    end
  
  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    use_legacy_build_api: true

    gym(scheme: "Zombiefy2016") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "Zombiefy2016") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

end
